#!/bin/bash
# echo "$1"
declare -a inputs_to_confirm

input_index=0

while read line; do
  inputs_to_confirm[input_index]=$line
  input_index=$((input_index + 1))
done


for i in "${!inputs_to_confirm[@]}"; do
  >&2 read -r -p "Look right?: '${inputs_to_confirm[$i]}' [y/n] " response </dev/tty

  if [ ${response} != "y" ]; then
    unset inputs_to_confirm[$i]
  fi
done

echo "${inputs_to_confirm[*]}" | xargs -n 1 echo
